%YAML 1.1
---
$schema: asdf://stsci.edu/datamodels/roman/schemas/rad_schema-1.1.0
id: asdf://stsci.edu/datamodels/roman/schemas/SSC/CGI/keywords/cgi_optical_config_named_positions-1.0.0

title: Optical configuration named positions
extName: SSC

type: object
properties:
  SPAMNAME:
    title: Closest SPAM named position
    description: Closest SPAM named position or possible positions
    type: string
    maxLength: 32
    archive_catalog:
      datatype: nvarchar(32)
      destination: [CGIExposure.spamname, CGIMosaic.spamname]
  FPAMNAME:
    title: Closest FPAM named position
    description: Closest FPAM named position or possible positions
    type: string
    maxLength: 32
    archive_catalog:
      datatype: nvarchar(32)
      destination: [CGIExposure.fpamname, CGIMosaic.fpamname]
  LSAMNAME:
    title: Closest LSAM named position
    description: Closest LSAM named position or possible positions
    type: string
    maxLength: 32
    archive_catalog:
      datatype: nvarchar(32)
      destination: [CGIExposure.lsamname, CGIMosaic.lsamname]
  FSAMNAME:
    title: Closest FSAM named position
    description: Closest FSAM named position or possible positions
    type: string
    maxLength: 32
    archive_catalog:
      datatype: nvarchar(32)
      destination: [CGIExposure.fsamname, CGIMosaic.fsamname]
  CFAMNAME:
    title: Closest CFAM named position
    description: Closest CFAM named position or possible positions
    type: string
    maxLength: 32
    archive_catalog:
      datatype: nvarchar(32)
      destination: [CGIExposure.cfamname, CGIMosaic.cfamname]
  DPAMNAME:
    title: Closest DPAM named position
    description: Closest DPAM named position or possible positions
    type: string
    maxLength: 32
    archive_catalog:
      datatype: nvarchar(32)
      destination: [CGIExposure.dpamname, CGIMosaic.dpamname]

required: [SPAMNAME, FPAMNAME, LSAMNAME, FSAMNAME, CFAMNAME, DPAMNAME]
